import pandas as pd
df = pd.read_csv('marketing_campaign.csv', sep=';')
print("--- Unique Education ---")
print(df['Education'].unique())
print("--- Unique Marital_Status ---")
print(df['Marital_Status'].unique())
print("--- Year_Birth Outliers ---")
print(df[df['Year_Birth'] < 1920][['Year_Birth']])
print("--- Income Outliers (max) ---")
print(df[df['Income'] > 200000][['Income']])
